name: 'Extract PR comment'
description: 'GitHub action to get PR comment URL'
author: 'Patryk Tomczyk @patzick'
inputs:
  token:
    description: 'Github API token'
    required: true
  platform:
    description: 'Platform which generated PR preview link. Supported: Vercel, Netlify'
    default: ''
  pattern:
    description: 'Pattern you have in comments with URLs'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'