name: 'Extract URL from comment'
description: 'Automate your workflow by extracting PR preview URLs (or any other URLs) from comments'
author: 'Patryk Tomczyk @patzick'
inputs:
  token:
    description: 'Github API token'
    required: true
  platform:
    description: 'Platform which generated PR preview link. Supported: Vercel, Netlify'
    default: ''
  pattern:
    description: 'Pattern you have in comments with URLs'
    default: ''
  index:
    description: 'Which URL from the comment should we extract'
    default: '1'
runs:
  using: 'node12'
  main: 'dist/index.js'